# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       libiptcdata

# >> macros
# << macros

Summary:    IPTC tag library
Version:    1.0.4
Release:    1
Group:      Development/Libraries
License:    LGPLv2
URL:        http://libiptcdata.sourceforge.net/
Source0:    %{name}-%{version}.tar.gz
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  python-devel
BuildRequires:  gettext
BuildRequires:  libtool

%description
libiptcdata is a library, written in C, for manipulating the International 
Press Telecommunications Council (IPTC) metadata stored within multimedia 
files such as images. This metadata can include captions and keywords, 
often used by popular photo management applications. The library provides 
routines for parsing, viewing, modifying, and saving this metadata. 
The library is licensed under the GNU Library General Public License 
(GNU LGPL). The libiptcdata package also includes a command-line utility, 
iptc, for editing IPTC data in JPEG files, as well as Python bindings.


%package devel
Summary:    Headers and libraries for libiptcdata application development
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The libiptcdata-devel package contains the libraries and include 
files that you can use to develop libiptcdata applications.


%package python
Summary:    Python bindings for libiptcdata
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   python-devel

%description python
The libiptcdata-python package contains a Python module that allows Python 
applications to use the libiptcdata API for reading and writing IPTC 
metadata in images.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --enable-python

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%find_lang iptc --all-name

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files -f iptc.lang
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING
%{_bindir}/*
%{_libdir}/lib*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/*.pc
%{_includedir}/libiptcdata
%{_datadir}/gtk-doc/html/libiptcdata
# << files devel

%files python
%defattr(-,root,root,-)
# >> files python
%doc python/README
%doc python/examples/*
%{python_sitearch}/*.so
# << files python

